In [1]:
import pandas as pd
import numpy as np
from ogb.nodeproppred import DglNodePropPredDataset

Using backend: pytorch


In [2]:
dataset = DglNodePropPredDataset(name='ogbn-arxiv', 
                                 root='../../data/dataset_dgl/')

In [3]:
graph = dataset[0][0]

In [4]:
graph

Graph(num_nodes=169343, num_edges=1166243,
      ndata_schemes={'year': Scheme(shape=(1,), dtype=torch.int64), 'feat': Scheme(shape=(128,), dtype=torch.float32)}
      edata_schemes={})

In [17]:
graph.nodes()

tensor([     0,      1,      2,  ..., 169340, 169341, 169342])

In [5]:
graph.edges()

(tensor([104447,  15858, 107156,  ...,  45118,  45118,  45118]),
 tensor([ 13091,  47283,  69161,  ..., 162473, 162537,  72717]))

In [6]:
graph.edges()[0].numpy()

array([104447,  15858, 107156, ...,  45118,  45118,  45118])

In [7]:
graph_np = np.zeros((graph.num_edges(), 3))
graph_np[:, 0] = graph.edges()[0].numpy()
graph_np[:, 2] = graph.edges()[1].numpy()
graph_np

array([[104447.,      0.,  13091.],
       [ 15858.,      0.,  47283.],
       [107156.,      0.,  69161.],
       ...,
       [ 45118.,      0., 162473.],
       [ 45118.,      0., 162537.],
       [ 45118.,      0.,  72717.]])

In [8]:
graph_df = pd.DataFrame(graph_np, dtype=int)
graph_df.head()

0  1       2
0  104447  0   13091
1   15858  0   47283
2  107156  0   69161
3  107156  0  136440
4  107156  0  107366

In [11]:
graph_df.shape

(1166243, 3)

In [13]:
graph_train = graph_df.sample(frac=0.96)
graph_validtest = graph_df.drop(graph_train.index)
print(graph_train.shape)
print(graph_validtest.shape)

(1119593, 3)
(46650, 3)


In [14]:
graph_valid = graph_validtest.sample(frac=0.5)
graph_test = graph_validtest.drop(graph_valid.index)
print(graph_valid.shape)
print(graph_test.shape)

(23325, 3)
(23325, 3)


In [15]:
graph_test.head()

0  1       2
4    107156  0  107366
45    79476  0   88828
76   113762  0   83423
86   122950  0     125
126  108479  0  105291

In [16]:
graph_valid.head()

0  1       2
203788   49553  0   96976
602088   29842  0  115394
481203   67020  0   29312
964136    7569  0   82632
658404  162309  0   19883

In [19]:
graph_df.to_csv('../../data/dataset_dglke/ogbn-arxiv-edges-full.tsv',
                sep='\t',
                index=False,
                header=False)
graph_train.to_csv('../../data/dataset_dglke/ogbn-arxiv-edges-train.tsv',
                   sep='\t',
                   index=False,
                   header=False)
graph_valid.to_csv('../../data/dataset_dglke/ogbn-arxiv-edges-valid.tsv',
                   sep='\t',
                   index=False,
                   header=False)
graph_test.to_csv('../../data/dataset_dglke/ogbn-arxiv-edges-test.tsv',
                   sep='\t',
                   index=False,
                   header=False)

In [23]:
entities = pd.DataFrame(graph.nodes().numpy())
entities.to_csv('../../data/dataset_dglke/entities.tsv',
                sep='\t',
                index=True,
                header=False)

In [24]:
relations = pd.DataFrame([0])
relations.to_csv('../../data/dataset_dglke/relations.tsv',
                 sep='\t',
                 index=True,
                 header=False)